import { expect, test } from '@playwright/test';
import type { Page } from '@playwright/test';
const commandInput = (page: Page) => page.getByRole('combobox', { name: 'コマンド入力' });
async function run(page: Page, command: string) {
  await page.getByRole('tab', { name: 'ターミナル', exact: true }).click();
  await commandInput(page).fill(command); await commandInput(page).press('Enter');
}
test.beforeEach(async ({ page }) => { await page.goto('/'); });
test('one program library categorizes tools, games and system and resets through commands', async ({ page }) => {
  await run(page, 'PROGRAMS');
  const library = page.getByRole('region', { name: 'プログラム一覧画面' });
  const selector = library.getByRole('textbox', { name: 'プログラムコードまたは番号' });
  const filters = library.getByRole('group', { name: 'プログラムの分類' });
  await expect(selector).toBeFocused(); await expect(library.getByRole('article')).toHaveCount(15);
  await filters.getByRole('button', { name: /^ツール/ }).click(); await expect(library.getByRole('article')).toHaveCount(7);
  await filters.getByRole('button', { name: /^ゲーム/ }).click(); await expect(library.getByRole('article')).toHaveCount(6);
  await filters.getByRole('button', { name: /^システム/ }).click(); await expect(library.getByRole('article')).toHaveCount(2);
  await run(page, 'GAMES'); await expect(selector).toBeFocused();
  await expect(filters.getByRole('button', { name: /^ゲーム/ })).toHaveAttribute('aria-pressed', 'true');
  await run(page, 'APPS'); await expect(library.getByRole('article')).toHaveCount(15);
  await expect(page.getByRole('tab', { name: 'プログラム一覧', exact: true })).toHaveCount(1);
  await selector.press('ArrowUp'); await expect(library.locator('.program-card.selected')).toContainText('SETTINGS');
  await expect(selector).toBeInViewport();
  await selector.press('Enter'); await expect(page.getByRole('region', { name: '設定', exact: true })).toBeVisible();
  await page.keyboard.press('Escape');
  await run(page, 'PROGRAMS TOOLS'); await expect(library.getByRole('article')).toHaveCount(7);
  await selector.fill('4'); await selector.press('Enter');
  await expect(page.getByRole('region', { name: '電卓', exact: true })).toBeVisible();
  await page.keyboard.press('Escape');
  await run(page, 'GAMES'); await selector.fill('calc'); await selector.press('Enter');
  await expect(page.getByRole('region', { name: '電卓', exact: true })).toBeVisible();
  await page.keyboard.press('Escape');
  await run(page, 'GAMES'); await selector.fill('1'); await selector.press('Enter');
  await expect(page.getByRole('region', { name: 'GUESS 数当てゲーム' })).toBeVisible();
  await page.getByRole('spinbutton', { name: '予想する数字' }).press('Escape');
  await run(page, 'RUN CALC "(12 + 8) * 3"');
  await expect(page.locator('.calculator-result')).toContainText('60');
});
test('shared menu includes VIM and GUESS, and library works on a narrow CRT screen', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const open = page.getByRole('button', { name: 'プログラムを開く', exact: true });
  await open.click();
  const menu = page.getByRole('menu', { name: 'プログラム', exact: true });
  await expect(menu.getByRole('group', { name: 'ツール' }).getByRole('menuitem')).toHaveCount(7);
  await expect(menu.getByRole('group', { name: 'ゲーム' }).getByRole('menuitem')).toHaveCount(6);
  await expect(menu.getByRole('group', { name: 'システム' }).getByRole('menuitem')).toHaveCount(2);
  await menu.getByRole('menuitem', { name: /VIM/ }).click();
  await expect(page.getByRole('textbox', { name: 'Vimエディタ本文' })).toBeFocused();
  await page.getByRole('button', { name: 'MEMO.TXTを閉じる', exact: true }).click();
  await open.click(); await menu.getByRole('menuitem', { name: /数当てゲーム/ }).click();
  await expect(page.getByRole('spinbutton', { name: '予想する数字' })).toBeFocused();
  await page.keyboard.press('Escape');
  await run(page, 'SETTINGS');
  await page.getByLabel('配色').selectOption('green'); await page.keyboard.press('Escape');
  await page.setViewportSize({ width: 375, height: 667 });
  if (await page.locator('.sidebar').count()) await page.locator('.sidebar-toggle').click();
  await open.click(); await menu.getByRole('menuitem', { name: /^プログラム一覧/ }).click();
  const library = page.getByRole('region', { name: 'プログラム一覧画面' });
  await expect(library).toBeVisible();
  const dimensions = await page.evaluate(() => ({ width: document.documentElement.clientWidth, scroll: document.documentElement.scrollWidth }));
  expect(dimensions.scroll).toBe(dimensions.width);
  await expect(library.getByRole('button', { name: '実行', exact: true })).toBeInViewport();
  await page.screenshot({ path: 'test-results/programs-mobile.png', fullPage: true });
  await library.getByRole('textbox').press('Escape'); await expect(commandInput(page)).toBeFocused();
  expect(errors).toEqual([]);
});
