import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { chromium } from '@playwright/test';

const outputDirectory = new URL('../docs/screenshots/', import.meta.url);
await mkdir(outputDirectory, { recursive: true });
const browser = await chromium.launch({ channel: 'msedge', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1180, height: 780 } });
  await page.goto('http://127.0.0.1:1420');
  const commandInput = page.locator('#terminal-command');
  await commandInput.waitFor();
  await page.screenshot({ path: fileURLToPath(new URL('terminal.png', outputDirectory)), fullPage: true });
  await page.locator('.command-item').filter({ hasText: 'TYPE' }).click();
  await page.screenshot({ path: fileURLToPath(new URL('command-guide.png', outputDirectory)), fullPage: true });
  await commandInput.fill('GAMES');
  await commandInput.press('Enter');
  await page.locator('.library-view').waitFor();
  await page.screenshot({ path: fileURLToPath(new URL('game-library.png', outputDirectory)), fullPage: true });
  await page.locator('.game-card .button.primary').click();
  await page.locator('.guess-form input').waitFor();
  await page.screenshot({ path: fileURLToPath(new URL('guess.png', outputDirectory)), fullPage: true });
  await page.locator('.game-topline .text-button').click();
  await commandInput.fill('PROGRAMS'); await commandInput.press('Enter');
  await page.getByRole('region', { name: 'プログラム一覧画面' }).waitFor();
  await page.screenshot({ path: fileURLToPath(new URL('programs.png', outputDirectory)), fullPage: true });
  await page.keyboard.press('Escape');
  await commandInput.fill('TODO'); await commandInput.press('Enter');
  await page.getByLabel('タスク名', { exact: true }).fill('RetroDOS v0.4を試す');
  await page.getByRole('button', { name: '追加', exact: true }).click();
  await page.getByRole('tab', { name: 'ターミナル', exact: true }).click();
  await commandInput.fill('CALC "(12 + 8) * 3"'); await commandInput.press('Enter');
  await page.getByRole('region', { name: '電卓', exact: true }).waitFor();
  await page.getByRole('button', { name: 'プログラムを開く', exact: true }).click();
  await page.getByRole('menu', { name: 'プログラム' }).waitFor();
  await page.screenshot({ path: fileURLToPath(new URL('apps.png', outputDirectory)), fullPage: true });
  await page.keyboard.press('Escape');
  await page.getByRole('tab', { name: 'ターミナル', exact: true }).click();
  await page.setViewportSize({ width: 375, height: 667 });
  await page.locator('.sidebar-toggle').click();
  await page.screenshot({ path: fileURLToPath(new URL('mobile.png', outputDirectory)), fullPage: true });
  console.log('Saved 7 screenshots to docs/screenshots.');
} finally { await browser.close(); }
